### PR TITLE
feat(template.njk):added-styles-for-enhancement

### PR DESCRIPTION
**Pull request by arteevraina**
# Screenshot
image
# Fixes Issue #330 
### Changes
- added styles in `styles.css`
- made changes in `views/templates.njk` 

Please Review @jeromesimeon @Michael-Grover  and suggest changes :)

### CODE REVIEW

**Comment by Michael-Grover** [comment]
No that's not good, the styling changes should only affect the author line, thanks for catching

**Comment by arteevraina** [comment]
Sure, got it. Will fix that.

**Comment by arteevraina** [comment]
@Michael-Grover @jeromesimeon made the changes. Please have a look and suggest any further changes :)

**Comment by jeromesimeon** [comment]
Thanks so much @arteevraina !

**Pull request merged**
