### PR TITLE
Add Open In Vscode Option

### PR DESCRIPTION
**Pull request by Ayman161803**
Signed-off-by: Ayman161803 <mohammedaymannawaz@gmail.com>

# Closes #<CORRESPONDING ISSUE NUMBER>

### Changes

- Modified ``run.js`` to pass a GitHub URL alongside other parameters to ``template.njk``
- Used the GitHub URL prop to set up a ``Open in VSCode`` option alongside ``Open In template studio``

### Flags

- ``node run.js`` has been run on yet this particular to prevent cluttering. I have however tested this out locally.

### Screenshots or Video

image

### Related Issues
- Issue #<NUMBER>
- Pull Request #<NUMBER>

### Author Checklist
- [x] Ensure you provide a [DCO sign-off](https://github.com/probot/dco#how-it-works) for your commits using the `--signoff` option of git commit.
- [x] Vital features and changes captured in unit and/or integration tests
- [x] Commits messages follow [AP format](https://github.com/accordproject/techdocs/blob/master/DEVELOPERS.md#commit-message-format)
- [ ] Extend the documentation, if necessary
- [x] Merging to `master` from `fork:branchname`

### CODE REVIEW

**Review by mttrbrts — APPROVED** [review]

**Comment by mttrbrts** [comment]
Love it! ❤️

**Comment by mttrbrts** [comment]
@Ayman161803 I'm happy for you to run `node run.js` to rebuild the static pages, do you want to add a commit to this PR with the changes?

**Comment by Ayman161803** [comment]
I have updated the PR after running ``node run.js``

**Review by mttrbrts — CHANGES_REQUESTED** [review]
@Ayman161803 I don't see the new  "Open in VS Code" link in the changed html files, similarly it does not appear in the Netlify preview. Can you review, please?

**Comment by Ayman161803** [comment]
I will have a look at this👍🏻

**Comment by Ayman161803** [comment]
@mttrbrts I am having trouble generating the HTML files for dropdowns after running ``node run.js``. The HTML in the sample screenshot was obtained after running ``SKIP_DROPDOWN=True node run.js`` which I think skips dropdowns. Can you please push changes to this branch or direct me on how to update all HTML files? Thank you.

**Comment by mttrbrts** [comment]
I've made some (rather hacky!) changes which add the button to all static pages. This approach of building static pages is breaking down.

I'm happy to make this kind of change to unblock you, but the maintainers should review the design of this build process.

To recreate you can run `ADD_VSCODE_BUTTON=true SKIP_DROPDOWNS=true npm run build`

**Review by mttrbrts — APPROVED** [review]

**Pull request merged**
