### PR TITLE
feat(LF logo): Added Linux Foundation logo to template site

### PR DESCRIPTION
**Pull request by VishalS99**
<OVERALL SUMMARY OF PULL REQUEST>

### Changes
- Added Linux Foundation logo

### CODE REVIEW

**Comment by VishalS99** [comment]
Well, it came smaller in my system. How small should it be?

**Comment by VishalS99** [comment]
I have changed the size of logo

**Comment by VishalS99** [comment]
@jeromesimeon could you check it out?

**Comment by Michael-Grover** [comment]
@VishalS99 please make the logo the same size as it is in the footer of https://www.accordproject.org/ and https://docs.accordproject.org/. 

See this comment in the original issue, which specifies the size and where it hyperlinks to:

https://github.com/accordproject/techdocs/issues/92#issuecomment-537059543

**Comment by Michael-Grover** [comment]
@VishalS99 I see from your code you followed the specs, I wonder why it looks different for Jerome. How can I preview this PR so I can see what it looks like on my computer?

**Pull request merged**
