### PR TITLE
fix closing tag in ecosystem

### PR DESCRIPTION
**Pull request by daniloff200**
small render fix

### CODE REVIEW

**Comment by irmerk** [comment]
This still needs a DCO

**Comment by daniloff200** [comment]
@irmerk  yeah, the idea of create a fix with github was not the best one, it doesn't allow me to pass DCO check :crying_cat_face:

**Comment by irmerk** [comment]
I believe it does it for me, though I'm not sure it's something I set up a long time ago or that I'm an admin for the organization.

**Comment by irmerk** [comment]
@jeromesimeon not sure I understand, how are they invalid?

**Comment by jeromesimeon** [comment]
No activity on this. I'm closing the PR.

**Pull request closed without merging**
