### PR TITLE
fix(src): swap buyer and seller - I259

### PR DESCRIPTION
**Pull request by Frozenaught**
# Issue #259 
This addresses a bug where the buyer and seller are swapped.

### Changes
- Swap the buyer and seller tags so that the seller pays the buyer.
  - minilatedelivery, minilatedelivery-capped and minilatedelivery-payment updated

### Flags
none
### Related Issues
- Issue #259 
- Pull Request #260

### CODE REVIEW

**Comment by mttrbrts** [comment]
Thanks @Frozenaught for your update! Can also bump the versions in package.json for each template, please? 

This is a breaking change so this should cause the minor version to be increased (See [Semver docs for 0.x versions](https://semver.org/#how-should-i-deal-with-revisions-in-the-0yz-initial-development-phase)

**Comment by Frozenaught** [comment]
I have updated it. hope this is good.

**Comment by mttrbrts** [comment]
Great work @Frozenaught! Approved and merging you should see your new templates at https://templates.accordproject.org soon

**Comment by mttrbrts** [comment]
Live at https://templates.accordproject.org/minilatedeliveryandpenalty-payment@0.4.0.html

Congrats on your first template!

**Pull request merged**
