### PR TITLE
fix(acceptance-of-delivery): remove unnecessary the

### PR DESCRIPTION
**Pull request by briannasims**
# No Issue
I just fixed a typo in this clause so that when inputting the name of Party A it was not preceded by "the."

### CODE REVIEW

**Comment by irmerk** [comment]
Oh no! I forgot these things! Yes let me know if you want help and we can pair again next week. But also feel free to try it out on your own

**Comment by briannasims** [comment]
I will do some googling and futzing and get back to you if I'm stuck!

**Comment by jeromesimeon** [comment]
> I will do some googling and futzing and get back to you if I'm stuck!
> […](#)

Sure! Happy to help as well. Couple of things that may help:
- Have Cicero on your machine so you can try and parse/run the template https://docs.accordproject.org/docs/started-installation.html
- Oddly, no great reference for testing. Some infos are here: https://docs.accordproject.org/docs/ref-testing.html

To test, if you have the template library repo, in the `acceptance-of-delivery` template you should be able to do:
```
bash-3.2$ cd ~/git/cicero-template-library/
bash-3.2$ lerna bootstrap 
lerna bootstrap 
info cli using local version of lerna
lerna notice cli v3.22.1
lerna info Bootstrapping 50 packages
lerna info Installing external dependencies
lerna info hoist Installing hoisted dependencies into root
lerna info hoist Pruning hoisted dependencies
lerna info hoist Finished pruning hoisted dependencies
lerna info hoist Finished bootstrapping root
lerna info Symlinking packages and binaries
lerna success Bootstrapped 50 packages
bash-3.2$ cd src/acceptance-of-delivery
bash-3.2$ npm run test
npm run test

> acceptance-of-delivery@0.14.0 test /Users/jeromesimeon/git/cicero-template-library/src/acceptance-of-delivery
> cucumber-js test -r .cucumber.js

.........................

5 scenarios (5 passed)
20 steps (20 passed)
0m10.874s
bash-3.2$ 
```

**Comment by jeromesimeon** [comment]
hi @briannasims do you need any help on this? Let me know!

**Comment by jeromesimeon** [comment]
No activity in this PR so I've redone it in #377

**Pull request closed without merging**
