### PR TITLE
fix(minilatedeliveryandpenalty): switch buyer and seller - I171

### PR DESCRIPTION
**Pull request by doomswatter**
Signed-off-by: doomswatter <44559839+doomswatter@users.noreply.github.com>

# Issue #171
Switched buyer and seller.

### Changes
- Switched buyer and seller.

### Flags
-

### Related Issues
- Issue #171

### CODE REVIEW

**Comment by irmerk** [comment]
I believe this is related to [techdocs issue 171](https://github.com/accordproject/techdocs/issues/171), which is about documentation and not the actual template in this repo.

**Comment by doomswatter** [comment]
In the file that I changed, the buyer and seller were in the wrong order. Should this be for a separate issue?

**Comment by irmerk** [comment]
Good point, maybe I'm confused.

**Comment by irmerk** [comment]
Tagging @4katie

**Comment by irmerk** [comment]
Pinging @jeromesimeon on this.

**Comment by irmerk** [comment]
Ah the branch it was from is deleted.

**Pull request closed without merging**
