### PR TITLE
Fixed errors in tests for promissory-note and promissory-note-md

### PR DESCRIPTION
**Pull request by lkcbharath**
# Issue #284
This PR has been opened to fix any errors while running `lerna run test`. There were logic errors that I've fixed.

### Changes
- Changed `tests/logic/logic.ergo` in the template packages `promissory-note` and `promissory-note-md`
  - Day count was reduced by 1 causing error
- Only one commit was made in reference to above: Fixed errors in tests for promissory-note and promissory-note-md

### Flags
Very important flag:
In `tests/logic/logic.ergo` for both `promissory-note` and `promissory-note-md`, there is an issue with `diffDurationAs()`.

With reference to the function call:
`diffDurationAs(dateTime("17 May 2018 13:53:33 EST"),contract.date,~org.accordproject.time.TemporalUnit.days).amount`
If the time is on or after `13:30:00`, the value returned is greater by 1 than what is intended, which is why the tests failed for both i.e. actual value was not equal to expected value. I do not know the reason for this.

Either the time could be set to before `13:30:00` for testing, or keeping time as it is, I have decremented the value by -1 when it was assigned to the `numberOfDays` variable within those files.

### Related Issues
N/A

### CODE REVIEW

**Comment by lkcbharath** [comment]
Screenshot from 2019-10-27 02-39-22

Because of the change I made, TravisCI fails. But this is on my local machine and the test runs fine.

**Comment by lkcbharath** [comment]
@jeromesimeon 
I can't get `now()` to work.
Besides, in `/src/promissory-note/test/logic.feature`, a static value is given for verifying the correctness of functionality, which is related to using a fixed date in the logic.

**Comment by jeromesimeon** [comment]
> @jeromesimeon
> I can't get `now()` to work.
> Besides, in `/src/promissory-note/test/logic.feature`, a static value is given for verifying the correctness of functionality, which is related to using a fixed date in `logic.ergo`.

@lkcbharath Could you please open an issue to describe your initial problem with the promissory note template?

**Comment by lkcbharath** [comment]
@jeromesimeon Here you go:
https://github.com/accordproject/cicero-template-library/issues/300

**Comment by jeromesimeon** [comment]
There is a new issue open about this #300 This needs further review.

**Pull request closed without merging**
