### PR TITLE
(test) migrate ip-payment tests to cucumber

### PR DESCRIPTION
**Pull request by irmerk**
Signed-off-by: irmerk <jolenelanglinais@gmail.com>

### CODE REVIEW

**Comment by irmerk** [comment]
So the Scenario in the test on this needs a `When the current time is "2019-01-31T16:34:00-05:00"`?

**Comment by jeromesimeon** [comment]
> So the Scenario in the test on this needs a `When the current time is "2019-01-31T16:34:00-05:00"`?

I'm not sure what the current time should be. I think you could probably pick any current time, and then the next quarter would have to be adjusted accordingly based on that.

Of course, you can also make several tests with different current times and set the corresponding next quarters in the response for the tests.

**Comment by irmerk** [comment]
> I'm not sure what the current time should be. I think you could probably pick any current time, and then the next quarter would have to be adjusted accordingly based on that.
> 
> Of course, you can also make several tests with different current times and set the corresponding next quarters in the response for the tests.

@jeromesimeon I'm not 100% sure I understood what you're saying, but I update the file to what I think you mean.

**Comment by jeromesimeon** [comment]
> > I'm not sure what the current time should be. I think you could probably pick any current time, and then the next quarter would have to be adjusted accordingly based on that.
> > Of course, you can also make several tests with different current times and set the corresponding next quarters in the response for the tests.
> 
> @jeromesimeon I'm not 100% sure I understood what you're saying, but I update the file to what I think you mean.

@irmerk I'm saying a few different things:

1. There is no replacement for the person writing the tests understanding the template logic. And what the should be tested should reflect the template logic.
2. I don't remember this one for sure on the top of my head, but _I believe_ it will work with any current time in any timezone.
3. It's very useful to improve the test coverage by adding new tests, so you could add tests with different current time and current timezones to check that the logic is doing what is expected.

**Comment by irmerk** [comment]
I updated the PR @jeromesimeon . If that’s still not what you were talking about, then we definitely need to go on zoom to discuss.

**Comment by jeromesimeon** [comment]
Will merge, then fix.

**Pull request merged**
